# obstacle_range: 5.0
# raytrace_range: 10.0
footprint: [[-0.40, -0.245], [-0.40, 0.245], [0.40, 0.245], [0.40, -0.245]]

transform_tolerance: 0.2
resolution: 0.05 

# static_map_layer:
#     map_topic: map
#     subscribe_to_updates: true

obstacles_layer:
  observation_sources: laser_scan
  laser_scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan,
  obstacle_range: 5.0, raytrace_range: 7.0, marking: true, clearing: true}

3d_obstacles_layer: 
  observation_sources: depth
  depth: {sensor_frame: camera_link, data_type: PointCloud2, topic: camera/depth/color/points,
     min_obstacle_height: 0.10, max_obstacle_height: 0.75, 
     obstacle_range: 1.8, raytrace_range: 2.2, marking: true, clearing: true}

# inflation_layer:
#     inflation_radius: 1.0

# plugins:
#   - {name: static_map_layer,    type: "costmap_2d::StaticLayer"}
#   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
#   - {name: obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
#   - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}